# listen address
listen = "127.0.0.1:6666"
# fallback remote address
fallback = "127.0.0.1:80"
h2fallback = "127.0.0.1:81"
PanelHost = "panel.example.org"
usagefile = "/usr/local/etc/wicktrojan/usage.db"

[TLS]
# certificate and private key files, leave empty and tls will not be enabled
certificate = "build/localhost+2.pem"
privatekey = "build/localhost+2-key.pem"
# if issuehost is not empty, wickproxy will try to issue a certificate from Let's encrypt.
# issuehost = ""
# if issuestore is not empty, issued certificate will be stored in that directory.
# issuestore = ""
NextProtos = ["h2","http/1.1"]

# [Websocket]
# Websocket mode
# host = "127.0.0.1:6666"
# path = "/wicktrojan"

[[users]]
username = "user1" # optional
password = "password"
# quota = 100

[[users]]
username = "user2"
password = "password2"
quota = 1

[[rules]]
# disallow private IP addresses
domain = "private"
allow = false

# [[rules]]
# # drop a domain
# domain = "a-domain-is-not-allowed.com"
# allow = false

# [[rules]]
# # UDP rules, allow 8.8.8.8
# UDP = true
# ip = "8.8.8.8"
# allow = true

# [[rules]]
# # UDP rules, allow 8.8.8.8
# port = "1"
# allow = false

# [[rules]]
# # UDP rules, allow 8.8.8.8
# cidr = "192.168.0.0/16"
# allow = false

# [[rules]]
# # UDP rules, do not allow udp
# UDP = true
# allow = false

# [[rules]]
# # last rule, allow requests left
# allow = true